-- Inserts tabela Formacao
INSERT INTO help.formacao(id, descricao) VALUES (1, 'BIBLIOTECONOMIA');
INSERT INTO help.formacao(id, descricao) VALUES (3, 'TEOLOGIA E CIÊNCIAS HUMANAS');
INSERT INTO help.formacao(id, descricao) VALUES (4, 'PEDAGOGIA');
INSERT INTO help.formacao(id, descricao) VALUES (5, 'LETRAS');
INSERT INTO help.formacao(id, descricao) VALUES (6, 'HISTÓRIA');
INSERT INTO help.formacao(id, descricao) VALUES (7, 'GEOGRAFIA');
INSERT INTO help.formacao(id, descricao) VALUES (8, 'FILOSOFIA');
INSERT INTO help.formacao(id, descricao) VALUES (9, 'CIÊNCIAS ECONÔMICAS');
INSERT INTO help.formacao(id, descricao) VALUES (10, 'ASSISTENTE SOCIAL');
INSERT INTO help.formacao(id, descricao) VALUES (11, 'ARQUIVOLOGIA COM EXTENSÃO EM BIBLIOTECONOMIA');
INSERT INTO help.formacao(id, descricao) VALUES (12, 'ARQUITETURA');
SELECT setval('help.seq_formacao', COALESCE((SELECT MAX(id) + 1 FROM help.formacao), 1), false);

INSERT INTO help.escolaridade(id, descricao) VALUES (1, 'Ensino Fundamental');
INSERT INTO help.escolaridade(id, descricao) VALUES (2, 'Ensino Médio');
INSERT INTO help.escolaridade(id, descricao) VALUES (3, 'Ensino Superior (Graduação)');
INSERT INTO help.escolaridade(id, descricao) VALUES (4, 'Ensino Superior (Pós-Graduação)');
INSERT INTO help.escolaridade(id, descricao) VALUES (5, 'Ensino Superior (Mestrado)');
INSERT INTO help.escolaridade(id, descricao) VALUES (6, 'Ensino Superior (Doutorado)');
INSERT INTO help.escolaridade(id, descricao) VALUES (7, 'Ensino Superior (Pós-Doutorado)');
INSERT INTO help.escolaridade(id, descricao) VALUES (8, 'Treinamento em Serviços de Biblioteca');
SELECT setval('help.seq_escolaridade', COALESCE((SELECT MAX(id) + 1 FROM help.escolaridade), 1), false);

INSERT INTO help.periodico(id, descricao) VALUES (1, 'até 10 títulos');
INSERT INTO help.periodico(id, descricao) VALUES (2, 'de 11 a 30 títulos');
INSERT INTO help.periodico(id, descricao) VALUES (3, 'de 31 a 50 títulos');
INSERT INTO help.periodico(id, descricao) VALUES (4, 'de 51 a 100 títulos');
INSERT INTO help.periodico(id, descricao) VALUES (5, 'acima de 100 títulos');
SELECT setval('help.seq_periodico', COALESCE((SELECT MAX(id) + 1 FROM help.periodico), 1), false);

INSERT INTO help.tipo_biblioteca(id, descricao) VALUES (1, 'MUNICIPAL');
INSERT INTO help.tipo_biblioteca(id, descricao) VALUES (2, 'ESTADUAL');
INSERT INTO help.tipo_biblioteca(id, descricao) VALUES (3, 'COMUNITÁRIO(A)');
SELECT setval('help.seq_tipo_biblioteca', COALESCE((SELECT MAX(id) + 1 FROM help.tipo_biblioteca), 1), false);

INSERT INTO help.intervalo_livro(id, descricao) VALUES (1, 'até 2000 livros');
INSERT INTO help.intervalo_livro(id, descricao) VALUES (2, 'de 2001 a 5000 livros');
INSERT INTO help.intervalo_livro(id, descricao) VALUES (3, 'de 5001 a 10000 livros');
INSERT INTO help.intervalo_livro(id, descricao) VALUES (4, 'de 10001 a 15000 livros');
INSERT INTO help.intervalo_livro(id, descricao) VALUES (5, 'de 15001 a 20000 livros');
INSERT INTO help.intervalo_livro(id, descricao) VALUES (6, 'de 20001 a 50000 livros');
INSERT INTO help.intervalo_livro(id, descricao) VALUES (7, 'acima de 50000 livros');
SELECT setval('help.seq_intervalo_livro', COALESCE((SELECT MAX(id) + 1 FROM help.intervalo_livro), 1), false);

INSERT INTO help.motivo_frequencia(id, descricao) VALUES (1, 'Trabalhos Escolares');
INSERT INTO help.motivo_frequencia(id, descricao) VALUES (2, 'Trabalhos Particulares');
INSERT INTO help.motivo_frequencia(id, descricao) VALUES (3, 'Lazer');
INSERT INTO help.motivo_frequencia(id, descricao) VALUES (4, 'Outros');
SELECT setval('help.seq_motivo_frequencia', COALESCE((SELECT MAX(id) + 1 FROM help.motivo_frequencia), 1), false);

Insert into help.municipio (id, nome, uf) values ('2300101','Abaiara', 'CE');
Insert into help.municipio (id, nome, uf) values ('2300150','Acarape', 'CE');
Insert into help.municipio (id, nome, uf) values ('2300200','Acaraú', 'CE');
Insert into help.municipio (id, nome, uf) values ('2300309','Acopiara', 'CE');
Insert into help.municipio (id, nome, uf) values ('2300408','Aiuaba', 'CE');
Insert into help.municipio (id, nome, uf) values ('2300507','Alcântaras', 'CE');
Insert into help.municipio (id, nome, uf) values ('2300606','Altaneira', 'CE');
Insert into help.municipio (id, nome, uf) values ('2300705','Alto Santo', 'CE');
Insert into help.municipio (id, nome, uf) values ('2300754','Amontada', 'CE');
Insert into help.municipio (id, nome, uf) values ('2300804','Antonina do Norte', 'CE');
Insert into help.municipio (id, nome, uf) values ('2300903','Apuiarés', 'CE');
Insert into help.municipio (id, nome, uf) values ('2301000','Aquiraz', 'CE');
Insert into help.municipio (id, nome, uf) values ('2301109','Aracati', 'CE');
Insert into help.municipio (id, nome, uf) values ('2301208','Aracoiaba', 'CE');
Insert into help.municipio (id, nome, uf) values ('2301257','Ararendá', 'CE');
Insert into help.municipio (id, nome, uf) values ('2301307','Araripe', 'CE');
Insert into help.municipio (id, nome, uf) values ('2301406','Aratuba', 'CE');
Insert into help.municipio (id, nome, uf) values ('2301505','Arneiroz', 'CE');
Insert into help.municipio (id, nome, uf) values ('2301604','Assaré', 'CE');
Insert into help.municipio (id, nome, uf) values ('2301703','Aurora', 'CE');
Insert into help.municipio (id, nome, uf) values ('2301802','Baixio', 'CE');
Insert into help.municipio (id, nome, uf) values ('2301851','Banabuiú', 'CE');
Insert into help.municipio (id, nome, uf) values ('2301901','Barbalha', 'CE');
Insert into help.municipio (id, nome, uf) values ('2301950','Barreira', 'CE');
Insert into help.municipio (id, nome, uf) values ('2302008','Barro', 'CE');
Insert into help.municipio (id, nome, uf) values ('2302057','Barroquinha', 'CE');
Insert into help.municipio (id, nome, uf) values ('2302107','Baturité', 'CE');
Insert into help.municipio (id, nome, uf) values ('2302206','Beberibe', 'CE');
Insert into help.municipio (id, nome, uf) values ('2302305','Bela Cruz', 'CE');
Insert into help.municipio (id, nome, uf) values ('2302404','Boa Viagem', 'CE');
Insert into help.municipio (id, nome, uf) values ('2302503','Brejo Santo', 'CE');
Insert into help.municipio (id, nome, uf) values ('2302602','Camocim', 'CE');
Insert into help.municipio (id, nome, uf) values ('2302701','Campos Sales', 'CE');
Insert into help.municipio (id, nome, uf) values ('2302800','Canindé', 'CE');
Insert into help.municipio (id, nome, uf) values ('2302909','Capistrano', 'CE');
Insert into help.municipio (id, nome, uf) values ('2303006','Caridade', 'CE');
Insert into help.municipio (id, nome, uf) values ('2303105','Cariré', 'CE');
Insert into help.municipio (id, nome, uf) values ('2303204','Caririaçu', 'CE');
Insert into help.municipio (id, nome, uf) values ('2303303','Cariús', 'CE');
Insert into help.municipio (id, nome, uf) values ('2303402','Carnaubal', 'CE');
Insert into help.municipio (id, nome, uf) values ('2303501','Cascavel', 'CE');
Insert into help.municipio (id, nome, uf) values ('2303600','Catarina', 'CE');
Insert into help.municipio (id, nome, uf) values ('2303659','Catunda', 'CE');
Insert into help.municipio (id, nome, uf) values ('2303709','Caucaia', 'CE');
Insert into help.municipio (id, nome, uf) values ('2303808','Cedro', 'CE');
Insert into help.municipio (id, nome, uf) values ('2303907','Chaval', 'CE');
Insert into help.municipio (id, nome, uf) values ('2303931','Choró', 'CE');
Insert into help.municipio (id, nome, uf) values ('2303956','Chorozinho', 'CE');
Insert into help.municipio (id, nome, uf) values ('2304004','Coreaú', 'CE');
Insert into help.municipio (id, nome, uf) values ('2304103','Crateús', 'CE');
Insert into help.municipio (id, nome, uf) values ('2304202','Crato', 'CE');
Insert into help.municipio (id, nome, uf) values ('2304236','Croatá', 'CE');
Insert into help.municipio (id, nome, uf) values ('2304251','Cruz', 'CE');
Insert into help.municipio (id, nome, uf) values ('2304269','Deputado Irapuan Pinheiro', 'CE');
Insert into help.municipio (id, nome, uf) values ('2304277','Ererê', 'CE');
Insert into help.municipio (id, nome, uf) values ('2304285','Eusébio', 'CE');
Insert into help.municipio (id, nome, uf) values ('2304301','Farias Brito', 'CE');
Insert into help.municipio (id, nome, uf) values ('2304350','Forquilha', 'CE');
Insert into help.municipio (id, nome, uf) values ('2304400','Fortaleza', 'CE');
Insert into help.municipio (id, nome, uf) values ('2304459','Fortim', 'CE');
Insert into help.municipio (id, nome, uf) values ('2304509','Frecheirinha', 'CE');
Insert into help.municipio (id, nome, uf) values ('2304608','General Sampaio', 'CE');
Insert into help.municipio (id, nome, uf) values ('2304657','Graça', 'CE');
Insert into help.municipio (id, nome, uf) values ('2304707','Granja', 'CE');
Insert into help.municipio (id, nome, uf) values ('2304806','Granjeiro', 'CE');
Insert into help.municipio (id, nome, uf) values ('2304905','Groaíras', 'CE');
Insert into help.municipio (id, nome, uf) values ('2304954','Guaiúba', 'CE');
Insert into help.municipio (id, nome, uf) values ('2305001','Guaraciaba do Norte', 'CE');
Insert into help.municipio (id, nome, uf) values ('2305100','Guaramiranga', 'CE');
Insert into help.municipio (id, nome, uf) values ('2305209','Hidrolândia', 'CE');
Insert into help.municipio (id, nome, uf) values ('2305233','Horizonte', 'CE');
Insert into help.municipio (id, nome, uf) values ('2305266','Ibaretama', 'CE');
Insert into help.municipio (id, nome, uf) values ('2305308','Ibiapina', 'CE');
Insert into help.municipio (id, nome, uf) values ('2305332','Ibicuitinga', 'CE');
Insert into help.municipio (id, nome, uf) values ('2305357','Icapuí', 'CE');
Insert into help.municipio (id, nome, uf) values ('2305407','Icó', 'CE');
Insert into help.municipio (id, nome, uf) values ('2305506','Iguatu', 'CE');
Insert into help.municipio (id, nome, uf) values ('2305605','Independência', 'CE');
Insert into help.municipio (id, nome, uf) values ('2305654','Ipaporanga', 'CE');
Insert into help.municipio (id, nome, uf) values ('2305704','Ipaumirim', 'CE');
Insert into help.municipio (id, nome, uf) values ('2305803','Ipu', 'CE');
Insert into help.municipio (id, nome, uf) values ('2305902','Ipueiras', 'CE');
Insert into help.municipio (id, nome, uf) values ('2306009','Iracema', 'CE');
Insert into help.municipio (id, nome, uf) values ('2306108','Irauçuba', 'CE');
Insert into help.municipio (id, nome, uf) values ('2306207','Itaiçaba', 'CE');
Insert into help.municipio (id, nome, uf) values ('2306256','Itaitinga', 'CE');
Insert into help.municipio (id, nome, uf) values ('2306306','Itapagé', 'CE');
Insert into help.municipio (id, nome, uf) values ('2306405','Itapipoca', 'CE');
Insert into help.municipio (id, nome, uf) values ('2306504','Itapiúna', 'CE');
Insert into help.municipio (id, nome, uf) values ('2306553','Itarema', 'CE');
Insert into help.municipio (id, nome, uf) values ('2306603','Itatira', 'CE');
Insert into help.municipio (id, nome, uf) values ('2306702','Jaguaretama', 'CE');
Insert into help.municipio (id, nome, uf) values ('2306801','Jaguaribara', 'CE');
Insert into help.municipio (id, nome, uf) values ('2306900','Jaguaribe', 'CE');
Insert into help.municipio (id, nome, uf) values ('2307007','Jaguaruana', 'CE');
Insert into help.municipio (id, nome, uf) values ('2307106','Jardim', 'CE');
Insert into help.municipio (id, nome, uf) values ('2307205','Jati', 'CE');
Insert into help.municipio (id, nome, uf) values ('2307254','Jijoca de Jericoacoara', 'CE');
Insert into help.municipio (id, nome, uf) values ('2307304','Juazeiro do Norte', 'CE');
Insert into help.municipio (id, nome, uf) values ('2307403','Jucás', 'CE');
Insert into help.municipio (id, nome, uf) values ('2307502','Lavras da Mangabeira', 'CE');
Insert into help.municipio (id, nome, uf) values ('2307601','Limoeiro do Norte', 'CE');
Insert into help.municipio (id, nome, uf) values ('2307635','Madalena', 'CE');
Insert into help.municipio (id, nome, uf) values ('2307650','Maracanaú', 'CE');
Insert into help.municipio (id, nome, uf) values ('2307700','Maranguape', 'CE');
Insert into help.municipio (id, nome, uf) values ('2307809','Marco', 'CE');
Insert into help.municipio (id, nome, uf) values ('2307908','Martinópole', 'CE');
Insert into help.municipio (id, nome, uf) values ('2308005','Massapê', 'CE');
Insert into help.municipio (id, nome, uf) values ('2308104','Mauriti', 'CE');
Insert into help.municipio (id, nome, uf) values ('2308203','Meruoca', 'CE');
Insert into help.municipio (id, nome, uf) values ('2308302','Milagres', 'CE');
Insert into help.municipio (id, nome, uf) values ('2308351','Milhã', 'CE');
Insert into help.municipio (id, nome, uf) values ('2308377','Miraíma', 'CE');
Insert into help.municipio (id, nome, uf) values ('2308401','Missão Velha', 'CE');
Insert into help.municipio (id, nome, uf) values ('2308500','Mombaça', 'CE');
Insert into help.municipio (id, nome, uf) values ('2308609','Monsenhor Tabosa', 'CE');
Insert into help.municipio (id, nome, uf) values ('2308708','Morada Nova', 'CE');
Insert into help.municipio (id, nome, uf) values ('2308807','Moraújo', 'CE');
Insert into help.municipio (id, nome, uf) values ('2308906','Morrinhos', 'CE');
Insert into help.municipio (id, nome, uf) values ('2309003','Mucambo', 'CE');
Insert into help.municipio (id, nome, uf) values ('2309102','Mulungu', 'CE');
Insert into help.municipio (id, nome, uf) values ('2309201','Nova Olinda', 'CE');
Insert into help.municipio (id, nome, uf) values ('2309300','Nova Russas', 'CE');
Insert into help.municipio (id, nome, uf) values ('2309409','Novo Oriente', 'CE');
Insert into help.municipio (id, nome, uf) values ('2309458','Ocara', 'CE');
Insert into help.municipio (id, nome, uf) values ('2309508','Orós', 'CE');
Insert into help.municipio (id, nome, uf) values ('2309607','Pacajus', 'CE');
Insert into help.municipio (id, nome, uf) values ('2309706','Pacatuba', 'CE');
Insert into help.municipio (id, nome, uf) values ('2309805','Pacoti', 'CE');
Insert into help.municipio (id, nome, uf) values ('2309904','Pacujá', 'CE');
Insert into help.municipio (id, nome, uf) values ('2310001','Palhano', 'CE');
Insert into help.municipio (id, nome, uf) values ('2310100','Palmácia', 'CE');
Insert into help.municipio (id, nome, uf) values ('2310209','Paracuru', 'CE');
Insert into help.municipio (id, nome, uf) values ('2310258','Paraipaba', 'CE');
Insert into help.municipio (id, nome, uf) values ('2310308','Parambu', 'CE');
Insert into help.municipio (id, nome, uf) values ('2310407','Paramoti', 'CE');
Insert into help.municipio (id, nome, uf) values ('2310506','Pedra Branca', 'CE');
Insert into help.municipio (id, nome, uf) values ('2310605','Penaforte', 'CE');
Insert into help.municipio (id, nome, uf) values ('2310704','Pentecoste', 'CE');
Insert into help.municipio (id, nome, uf) values ('2310803','Pereiro', 'CE');
Insert into help.municipio (id, nome, uf) values ('2310852','Pindoretama', 'CE');
Insert into help.municipio (id, nome, uf) values ('2310902','Piquet Carneiro', 'CE');
Insert into help.municipio (id, nome, uf) values ('2310951','Pires Ferreira', 'CE');
Insert into help.municipio (id, nome, uf) values ('2311009','Poranga', 'CE');
Insert into help.municipio (id, nome, uf) values ('2311108','Porteiras', 'CE');
Insert into help.municipio (id, nome, uf) values ('2311207','Potengi', 'CE');
Insert into help.municipio (id, nome, uf) values ('2311231','Potiretama', 'CE');
Insert into help.municipio (id, nome, uf) values ('2311264','Quiterianópolis', 'CE');
Insert into help.municipio (id, nome, uf) values ('2311306','Quixadá', 'CE');
Insert into help.municipio (id, nome, uf) values ('2311355','Quixelô', 'CE');
Insert into help.municipio (id, nome, uf) values ('2311405','Quixeramobim', 'CE');
Insert into help.municipio (id, nome, uf) values ('2311504','Quixeré', 'CE');
Insert into help.municipio (id, nome, uf) values ('2311603','Redenção', 'CE');
Insert into help.municipio (id, nome, uf) values ('2311702','Reriutaba', 'CE');
Insert into help.municipio (id, nome, uf) values ('2311801','Russas', 'CE');
Insert into help.municipio (id, nome, uf) values ('2311900','Saboeiro', 'CE');
Insert into help.municipio (id, nome, uf) values ('2311959','Salitre', 'CE');
Insert into help.municipio (id, nome, uf) values ('2312007','Santana do Acaraú', 'CE');
Insert into help.municipio (id, nome, uf) values ('2312106','Santana do Cariri', 'CE');
Insert into help.municipio (id, nome, uf) values ('2312205','Santa Quitéria', 'CE');
Insert into help.municipio (id, nome, uf) values ('2312304','São Benedito', 'CE');
Insert into help.municipio (id, nome, uf) values ('2312403','São Gonçalo do Amarante', 'CE');
Insert into help.municipio (id, nome, uf) values ('2312502','São João do Jaguaribe', 'CE');
Insert into help.municipio (id, nome, uf) values ('2312601','São Luís do Curu', 'CE');
Insert into help.municipio (id, nome, uf) values ('2312700','Senador Pompeu', 'CE');
Insert into help.municipio (id, nome, uf) values ('2312809','Senador Sá', 'CE');
Insert into help.municipio (id, nome, uf) values ('2312908','Sobral', 'CE');
Insert into help.municipio (id, nome, uf) values ('2313005','Solonópole', 'CE');
Insert into help.municipio (id, nome, uf) values ('2313104','Tabuleiro do Norte', 'CE');
Insert into help.municipio (id, nome, uf) values ('2313203','Tamboril', 'CE');
Insert into help.municipio (id, nome, uf) values ('2313252','Tarrafas', 'CE');
Insert into help.municipio (id, nome, uf) values ('2313302','Tauá', 'CE');
Insert into help.municipio (id, nome, uf) values ('2313351','Tejuçuoca', 'CE');
Insert into help.municipio (id, nome, uf) values ('2313401','Tianguá', 'CE');
Insert into help.municipio (id, nome, uf) values ('2313500','Trairi', 'CE');
Insert into help.municipio (id, nome, uf) values ('2313559','Tururu', 'CE');
Insert into help.municipio (id, nome, uf) values ('2313609','Ubajara', 'CE');
Insert into help.municipio (id, nome, uf) values ('2313708','Umari', 'CE');
Insert into help.municipio (id, nome, uf) values ('2313757','Umirim', 'CE');
Insert into help.municipio (id, nome, uf) values ('2313807','Uruburetama', 'CE');
Insert into help.municipio (id, nome, uf) values ('2313906','Uruoca', 'CE');
Insert into help.municipio (id, nome, uf) values ('2313955','Varjota', 'CE');
Insert into help.municipio (id, nome, uf) values ('2314003','Várzea Alegre', 'CE');
Insert into help.municipio (id, nome, uf) values ('2314102','Viçosa do Ceará', 'CE');